### ISSUE TITLE
Create a package for arch linux

### ISSUE THREAD

**Issue by CRAG666** [otsaloma/catapult#12]
https://aur.archlinux.org/packages/catapult I would like to see this package included in the README if arch users don't have to manually compile catapult. I would also like you to review the PKBUILD in case I have any errors or if I am missing a dependency

**Comment by otsaloma** [comment]
Checked the PKGBUILD

* The version should be 0.3.2, not 3.2
* URL should point to https://otsaloma.io/catapult
* I think you should package the latest release, not git

Otherwise, I think it looks fine. I'm not that familiar with dependencies on Arch though.

I can add a link in the README once the PKGBUILD is in order.

**Comment by CRAG666** [comment]
I have already made all the requested changes, thank you very much for the suggestions

**Comment by otsaloma** [comment]
Thanks, added to the README file.

https://github.com/otsaloma/catapult/commit/64e6fe5250c9315edd5c84d8017ff5f0e55e81aa

**Comment by sandboiii** [comment]
@CRAG666 I use your aur package, but you haven't updated it since 0.9 version. If you don't have time or interest to maintain this package, could you please disown it or set me as a co-maintainer so I can keep it updated? I've sent you email message, but never got any reply. So, I've decided to write here in case you did not receive it.
